import type { ContainerConfig } from "../config/types.js";
import { composeRuntimeEnv, resolveEnvironmentEnv } from "../env/resolve.js";
import type { NameValueEntry, ResolvedEnvironment } from "../config/types.js";
import { imageRoot as computeImageRoot } from "../docker/image.js";
import YAML from "yaml";

function collectNamedVolumes(containers: ContainerConfig[]): string[] {
  const names = new Set<string>();
  for (const container of containers) {
    for (const volume of container.volumes ?? []) {
      if (volume.name) {
        names.add(volume.name);
      }
    }
  }
  return [...names];
}

function renderContainerService(
  container: ContainerConfig,
  network: string,
  runtimeEnv: Array<{ name: string; value: string }>,
): Record<string, unknown> {
  const service: Record<string, unknown> = {
    image: `\${DOCKER_IMAGE_ROOT}/${container.image}:\${DOCKER_TAG}`,
    container_name: container.id,
    restart: "unless-stopped",
    networks: [network],
  };

  if (container.ports?.length) {
    service.ports = container.ports.map((port) => `${port.host}:${port.container}`);
  }

  if (container.expose?.length) {
    service.expose = container.expose.map(String);
  }

  if (runtimeEnv.length) {
    service.environment = Object.fromEntries(runtimeEnv.map((entry) => [entry.name, entry.value]));
  }

  if (container.volumes?.length) {
    service.volumes = container.volumes.map((volume) => {
      if (volume.name) {
        return `${volume.name}:${volume.container}`;
      }
      if (volume.host) {
        return `${volume.host}:${volume.container}`;
      }
      throw new Error(`Container "${container.id}" has a volume without name or host.`);
    });
  }

  if (container.dependsOn?.length) {
    service.depends_on = container.dependsOn;
  }

  return service;
}

export function buildComposeDocument(
  resolved: ResolvedEnvironment,
  environmentEnv: NameValueEntry[],
  containers: ContainerConfig[],
): Record<string, unknown> {
  const envSymbols = resolveEnvironmentEnv(environmentEnv);
  const services: Record<string, unknown> = {};

  for (const container of containers) {
    const runtimeEnv = composeRuntimeEnv(environmentEnv, container.env ?? [], envSymbols);
    services[container.id] = renderContainerService(container, resolved.network, runtimeEnv);
  }

  const namedVolumes = collectNamedVolumes(containers);
  const doc: Record<string, unknown> = {
    services,
    networks: {
      [resolved.network]: { name: resolved.network },
    },
  };

  if (namedVolumes.length > 0) {
    doc.volumes = Object.fromEntries(namedVolumes.map((name) => [name, {}]));
  }

  return doc;
}

export function buildEnvFileContent(resolved: ResolvedEnvironment, envKey: string): string {
  const root = computeImageRoot(resolved);
  return [
    "# Generated by dockup — do not edit by hand",
    `# env=${envKey}`,
    `DOCKER_IMAGE_ROOT=${root}`,
    `DOCKER_TAG=${resolved.tag}`,
    "",
  ].join("\n");
}

export function serializeCompose(doc: Record<string, unknown>): string {
  return YAML.stringify(doc, { lineWidth: 0 }).trimEnd() + "\n";
}
